services:
  youtube-live:
    build: .
    container_name: youtube-live
    ports:
      - "6095:6095"
    volumes:
      - ./data:/data
    environment:
      - M3U_DIR=/data
      - HOST_IP=127.0.0.1
      - SERVER_PORT=6095
    restart: unless-stopped
