services:
  youtube-live:
    build: .
    container_name: youtube-live
    ports:
      - "6095:6095"
    volumes:
      - /docker/appdata/youtube-live/data:/data
    environment:
      - M3U_DIR=/data
      - HOST_IP=192.168.50.57
      - SERVER_PORT=6095
    restart: unless-stopped
