services:
  yt-hdhr:
    build: .
    container_name: yt-hdhr
    network_mode: host
    volumes:
      - /docker/appdata/yt-hdhr/data:/data
    environment:
      - HOST_IP=192.168.50.57
    restart: unless-stopped
